runtime: go119
nobuild_files: app/.*
app_engine_apis: true

handlers:
- url: /favicon.ico
  static_files: view/images/Glukit.ico
  upload: view/images/Glukit.ico
  secure: always
  
- url: /js
  static_dir: view/js
  secure: always

- url: /css
  static_dir: view/css
  secure: always

- url: /bower_components
  static_dir: view/bower_components
  secure: always

- url: /images
  static_dir: view/images
  secure: always

- url: /fonts
  static_dir: view/fonts
  secure: always

- url: /browse
  script: auto
  login: required
  secure: always

- url: /report
  script: auto
  login: required
  secure: always

- url: /data
  script: auto
  login: required
  secure: always

- url: /demo.report
  script: auto
  secure: always

- url: /googleauth
  script: auto
  login: required
  secure: always

- url: /initpower
  script: auto  
  login: admin
  secure: always

- url: /v1/calibrations
  script: auto 

- url: /v1/injections
  script: auto 

- url: /v1/meals
  script: auto 

- url: /v1/glucosereads
  script: auto  

- url: /v1/exercises
  script: auto 

- url: /authorize
  script: auto
  login: required  
  secure: always

- url: /token
  script: auto  

- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup
