application: glukit
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: view/images/Glukit.ico
  upload: view/images/Glukit.ico

- url: /js
  static_dir: view/js

- url: /css
  static_dir: view/css

- url: /images
  static_dir: view/images

- url: /graph
  script: _go_app
  login: required

- url: /report
  script: _go_app
  login: required

- url: /demo.report
  script: _go_app

- url: /realuser
  script: _go_app
  login: required

- url: /initpower
  script: _go_app  
  login: admin

- url: /alr
  script: _go_app
  login: required

- url: /v1/calibrations
  script: _go_app
  login: required 

- url: /v1/injections
  script: _go_app
  login: required 

- url: /v1/foods
  script: _go_app
  login: required 

- url: /v1/glucosereads
  script: _go_app
  login: required 

- url: /.*
  script: _go_app

inbound_services:
- warmup
