application: glukit
version: 1beta
runtime: go
api_version: go1
nobuild_files: app/.*

handlers:
- url: /favicon.ico
  static_files: view/images/Glukit.ico
  upload: view/images/Glukit.ico

- url: /js
  static_dir: view/js

- url: /css
  static_dir: view/css

- url: /bower_components
  static_dir: view/bower_components

- url: /images
  static_dir: view/images

- url: /fonts
  static_dir: view/fonts

- url: /browse
  script: _go_app
  login: required

- url: /report
  script: _go_app
  login: required

- url: /data
  script: _go_app
  login: required

- url: /demo.report
  script: _go_app

- url: /googleauth
  script: _go_app
  login: required

- url: /initpower
  script: _go_app  
  login: admin

- url: /v1/calibrations
  script: _go_app 

- url: /v1/injections
  script: _go_app 

- url: /v1/meals
  script: _go_app 

- url: /v1/glucosereads
  script: _go_app  

- url: /v1/exercises
  script: _go_app 

- url: /authorize
  script: _go_app
  login: required  
  secure: always

- url: /token
  script: _go_app  
  secure: always

- url: /.*
  script: _go_app

inbound_services:
- warmup
